-- Swift Shoe Shop - Supabase schema + RLS
-- Run this first in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- Types
-- -----------------------------------------------------------------------------

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public'
      and t.typname = 'order_status'
  ) then
    create type public.order_status as enum (
      'pending',
      'processing',
      'shipped',
      'delivered',
      'cancelled'
    );
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- Profiles (auth-linked user metadata)
-- -----------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    'customer'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- -----------------------------------------------------------------------------
-- Products
-- -----------------------------------------------------------------------------

create table if not exists public.products (
  id integer generated by default as identity primary key,
  name text not null,
  brand text not null,
  description text not null,
  price numeric(10, 2) not null check (price >= 0),
  original_price numeric(10, 2),
  image_url text not null,
  images jsonb not null default '[]'::jsonb check (jsonb_typeof(images) = 'array'),
  category text not null,
  sizes jsonb not null default '[]'::jsonb check (jsonb_typeof(sizes) = 'array'),
  rating numeric(3, 2) not null default 4.50,
  review_count integer not null default 0,
  stock integer not null default 0,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_products_category on public.products(category);
create index if not exists idx_products_featured on public.products(featured);
create index if not exists idx_products_name_trgm on public.products using gin (to_tsvector('simple', name));

-- -----------------------------------------------------------------------------
-- Orders
-- -----------------------------------------------------------------------------

create table if not exists public.orders (
  id integer generated by default as identity primary key,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  address text not null,
  city text not null,
  status public.order_status not null default 'pending',
  items jsonb not null default '[]'::jsonb check (jsonb_typeof(items) = 'array'),
  subtotal numeric(10, 2) not null,
  delivery numeric(10, 2) not null default 5.00,
  discount numeric(10, 2) not null default 0.00,
  total numeric(10, 2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_orders_customer_email on public.orders(customer_email);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_orders_set_updated_at on public.orders;

create trigger trg_orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- Categories (derived from products)
-- -----------------------------------------------------------------------------

create or replace view public.categories as
select
  row_number() over (order by p.category)::int as id,
  p.category as name,
  lower(regexp_replace(trim(p.category), '\\s+', '-', 'g')) as slug,
  count(*)::int as product_count
from public.products p
group by p.category;

create or replace function public.list_categories()
returns table (
  id integer,
  name text,
  slug text,
  "productCount" integer
)
language sql
stable
as $$
  select
    c.id,
    c.name,
    c.slug,
    c.product_count as "productCount"
  from public.categories c
  order by c.name;
$$;

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;

drop policy if exists "Profiles are viewable by owner" on public.profiles;
create policy "Profiles are viewable by owner"
on public.profiles
for select
to authenticated
using (id = auth.uid());

drop policy if exists "Profiles are editable by owner" on public.profiles;
create policy "Profiles are editable by owner"
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "Admins can read all profiles" on public.profiles;
create policy "Admins can read all profiles"
on public.profiles
for select
to authenticated
using (public.is_admin());

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products
for delete
to authenticated
using (public.is_admin());

-- NOTE: This keeps order reads open to preserve current storefront order-confirmation flow.
-- For stricter production privacy, replace this with owner/admin-only access.
drop policy if exists "Public can read orders" on public.orders;
create policy "Public can read orders"
on public.orders
for select
to anon, authenticated
using (true);

drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
on public.orders
for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders"
on public.orders
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete orders" on public.orders;
create policy "Admins can delete orders"
on public.orders
for delete
to authenticated
using (public.is_admin());

-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------

grant usage on schema public to anon, authenticated;

grant select on public.products to anon, authenticated;
grant select on public.categories to anon, authenticated;
grant execute on function public.list_categories() to anon, authenticated;

grant select, insert on public.orders to anon, authenticated;

grant select, update on public.profiles to authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;
